console.log("TRAD LOADED");
var trad = [
    "{\"title\": \"Relic of a Forgotten Saint - Left Leg\", \"src\": \"imgs/trad/leftLeg.JPG\", \"description\": \"This piece uses motifs from science fiction, gothic archtecture, and catholic relics. \", \"medium\": \"Pencil and Chalk on Old Goldfish Box\"}",
    "{\"title\": \"Celadon\", \"src\": \"imgs/trad/celadon.jpg\", \"description\": \"A portrait of good friend\", \"medium\": \"Arcylic\"}",
    "{\"title\": \"Relic of a Forgotten Saint - Full Body\", \"src\": \"imgs/trad/fullBody.JPG\", \"description\": \"An installation made of discarded items either from my life or that I found. This piece examines how objects are given value and the nature of worship.\", \"medium\": \"\"}",
    "{\"title\": \"Relic of a Forgotten Saint - Spine and Ribs\", \"src\": \"imgs/trad/spingAndRibs.JPG\", \"description\": \"\", \"medium\": \"Marker on Wax Paper\"}",
    "{\"title\": \"The Magician\", \"src\": \"imgs/trad/magician.jpg\", \"description\": \"A tarot card that symbolizes a turning point and the connection to one's earthly self to one's divine self. This piece heavily draws influence from art noveau.\", \"medium\": \"Watercolor and Color Pencil on Wood\"}",
    "{\"title\": \"Cut Up Stars\", \"src\": \"imgs/trad/1_Ngo_CutUpStars.jpg\", \"description\": \"A still life of objects important to me such as the scissors I use to cut my hair and paper stars given to me by a best friend.\", \"medium\": \"Acrylic on Canvas Board\"}",
    "{\"title\": \"Relic of a Forgotten Saint - Left Hand\", \"src\": \"imgs/trad/leftHand.JPG\", \"description\": \"This piece is intentionally unfinished to create a sense of age.\", \"medium\": \"Color Pencil on Ikea Desk\"}",
    "{\"title\": \"Fall Morning\", \"src\": \"imgs/trad/fallMorning.jpg\", \"description\": \"Obersvational ink painting of CMU campus\", \"medium\": \"Ink on Paper\"}",
    "{\"title\": \"Relic of a Forgotten Saint - Right Forearm\", \"src\": \"imgs/trad/rightForearm.jpg\", \"description\": \"This piece is inspired by the palace of Versailles with its Rococo inspired motifs and color scheme. I aimed to create a timelessness to the figure to show that this person exits in the past present and future. \", \"medium\": \"Color Pencil on Wood\"}",
    "{\"title\": \"Memories of Street\", \"src\": \"imgs/trad/MemStreetGood.jpg\", \"description\": \"I wanted to recreate a childhood street from memory imbued with the feelings of nostalgia and childhood. I emulated the style of Quentin Blake, the illustrator for my favorite author, Roald Dahl. I free handed the perspective and used loose strokes for the line art to evoke the shakiness and imperfections of memory.\", \"medium\": \"Water Color\"}",
    "{\"title\": \"View of Bull Creek\", \"src\": \"imgs/trad/2_Ngo_ViewOfBullCreek.jpg\", \"description\": \"An obervational painting of a creek in hometome on a cold chilly Texas morning. I attempt to convey the temperature of this scene through my use of color.\", \"medium\": \"Water Color\"}",
    "{\"title\": \"What Lies Beneath the Skin\", \"src\": \"imgs/trad/birdName.jpg\", \"description\": \"Winner of the Texas Mental Health Association Art contest. This piece was created in a state of severe depression. I wanted to depict my own struggles with mental health. \", \"medium\": \"Acrylic\"}",
    "{\"title\": \"Harold\", \"src\": \"imgs/trad/haroldFinal.JPG\", \"description\": \"This is a silly painting depicting my favorite animal in my favorite colors. I wanted to make the lowest stakes creating possible in attempts to bring myself and other joy during a stressful period in my life.\", \"medium\": \"Acrylic on Cardboard\"}",
    "{\"title\": \"How to Play the Piano\", \"src\": \"imgs/trad/ToPlayThePiano.JPG\", \"description\": \"This is a conceptual art piece about how we encode information. We encode sound using sheet music, so I wanted to create a parallel in which we encode movement instead. The performance aspect of music is thrilling and I wanted to be able to share that experience with non musicians so they can feel all of the emotions and thoughts of a piano performance. This piece is 10ft tall and I aim to allow the viewer to follow along and immerse themselves in this song with me.\", \"medium\": \"Ink on Paper\"}",
    "{\"title\": \"Imposter Syndrome\", \"src\": \"imgs/trad/imposter_syndrome.JPG\", \"description\": \"This piece examines the feelings of being transplanted somewhere new and feeling like you shouldn't be there. I want to express the feelings of suffocation and insincerity.  \", \"medium\": \"Acrylic\"}",
    "{\"title\": \"Relic of a Forgotten Saint - Right Leg\", \"src\": \"imgs/trad/rightLeg.JPG\", \"description\": \"These were created on top of dicarded objects that I found. My goal was to create value from things that are worthless similar to how Catholic relics are made.\", \"medium\": \"Color Pencil on VHS and Cardboard, Acrylic on Denim\"}",
    "{\"title\": \"Relic of a Forgotten Saint - Spine\", \"src\": \"imgs/trad/Spine.JPG\", \"description\": \"This piece is the focal point and crowning jewel of the Forgotten Saint collection. I incorporated futuristic, steam punk, and catholic art motifs within this piece to create the feeling of this figure existing in both the past present and future. I used a paper bag to create flesh texture.\", \"medium\": \"Color pencil on paper bag\"}",
    "{\"title\": \"Sweet Liar\", \"src\": \"imgs/trad/SweetLiarFinal.jpg\", \"description\": \"A self portait examining my feelings of self worth\", \"medium\": \"Color Pencil on Wood\"}",
    "{\"title\": \"Nocturne\", \"src\": \"imgs/trad/musicboi2.JPG\", \"description\": \"The personification of a Chopin Nocturne. I wanted to create a sense of androgyny\", \"medium\": \"Water color\"}"
 ]